export const CONTRACT_COLUMNS = [
  {
    name: "Id",
    selector: "id",
    sortable: false,
    omit: true,
    minWidth: "250px",
  },
  {
    name: "Contract",
    selector: "contract",
    sortable: true,
    minWidth: "250px",
  },
  {
    name: "Owner Name",
    selector: "ownerName",
    sortable: true,
    minWidth: "250px",
  },
  {
    name: "Age(0)",
    selector: "ageO",
    sortable: true,
    minWidth: "250px",
    hide: "md",
  },
  {
    name: "Annuitant Name",
    selector: "annuitantName",
    sortable: true,
    minWidth: "250px",
    hide: "sm",
  },
  {
    name: "Age(A)",
    selector: "ageA",
    sortable: true,
    minWidth: "250px",
    hide: "md",
  },
  {
    name: "Issued",
    selector: "issued",
    sortable: true,
    minWidth: "250px",
    hide: "sm",
  },
  {
    name: "Product",
    selector: "product",
    sortable: true,
  },
  {
    name: "LOB",
    selector: "lob",
    sortable: true,
    hide: "md",
  },
  {
    name: "INH",
    selector: "inh",
    sortable: true,
    hide: "md",
  },
  {
    name: "eStmt",
    selector: "eStmt",
    sortable: true,
    hide: "md",
  },
  {
    name: "CIS",
    selector: "cis",
    sortable: true,
    hide: "md",
  },
  {
    name: "eTax",
    selector: "eTax",
    sortable: true,
    hide: "md",
  },
  {
    name: "Tel/Auth",
    selector: "telAuth",
    sortable: true,
    hide: "md",
  },
  {
    name: "Value",
    selector: "value",
    sortable: true,
  },
];
