export const CONTRACT_COLUMNS = [
  {
    title: "Id",
    data: "id",
    sortable: false,
  },
  {
    title: "Contract",
    data: "contract",
    sortable: true,
    hide: "sm",
  },
  {
    title: "Owner Name",
    data: "ownerName",
    sortable: true,
    hide: "sm",
  },
  {
    title: "Age(0)",
    data: "ageO",
    sortable: true,
    hide: "sm",
  },
  {
    title: "Annuitant Name",
    data: "annuitantName",
    sortable: true,
    hide: "sm",
  },
  {
    title: "Age(A)",
    data: "ageA",
    sortable: true,
    hide: "sm",
  },
  {
    title: "Issued",
    data: "issued",
    sortable: true,
    hide: "sm",
  },
  {
    title: "Product",
    data: "product",
    sortable: true,
    hide: "sm",
  },
  {
    title: "LOB",
    data: "lob",
    sortable: true,
    hide: "sm",
  },
  {
    title: "INH",
    data: "inh",
    sortable: true,
    hide: "sm",
  },
  {
    title: "eStmt",
    data: "eStmt",
    sortable: true,
    hide: "sm",
  },
  {
    title: "CIS",
    data: "cis",
    sortable: true,
    hide: "sm",
  },
  {
    title: "eTax",
    data: "eTax",
    sortable: true,
    hide: "sm",
  },
  {
    title: "Tel/Auth",
    data: "telAuth",
    sortable: true,
    hide: "sm",
  },
  {
    title: "Value",
    data: "value",
    sortable: true,
    hide: "sm",
  },
];
